import { createContext, useContext, useState } from 'react';

/**
 * LanguageContext — Provides i18n translations across the app.
 * Supports: English, Hindi, Kannada, Tamil, Telugu
 */

const translations = {
  en: {
    // Navbar
    home: 'Home',
    liveMap: 'Live Map',
    dashboard: 'Dashboard',
    login: 'Login',
    logout: 'Logout',
    
    // Hero
    heroTitle1: 'Reduce Waste,',
    heroTitle2: 'Feed Communities',
    heroSubtitle: 'Anna Setu connects surplus food from donors with local NGOs and volunteers to ensure no one goes hungry.',
    getStarted: 'Get Started Now',
    goToDashboard: 'Go to Dashboard',
    welcomeBack: 'Welcome back,',
    
    // Stats
    mealsRedistributed: 'Meals Redistributed',
    activeDonors: 'Active Donors',
    ngosAndShelters: 'NGOs & Shelters',
    volunteers: 'Volunteers',
    
    // How It Works
    howItWorks: 'How It Works',
    simpleSteps: 'Simple steps to make a difference',
    donorListsFood: 'Donor Lists Food',
    donorListsFoodDesc: 'Restaurants and individuals list surplus food with details and expiry time.',
    receiverRequests: 'Receiver Requests',
    receiverRequestsDesc: 'NGOs and shelters browse available food and send a request.',
    volunteerDelivers: 'Volunteer Delivers',
    volunteerDeliversDesc: 'Volunteers pick up the food and deliver it to the receiver.',
    impactMade: 'Impact Made!',
    impactMadeDesc: 'Food reaches those who need it. Zero waste, zero hunger.',
    
    // Roles
    joinAs: 'Join As',
    chooseRole: 'Choose your role and start making an impact',
    donor: 'Donor',
    receiver: 'Receiver',
    volunteer: 'Volunteer',
    donorDesc: 'Have surplus food? List it on Anna Setu and help feed the needy.',
    receiverDesc: 'NGOs, shelters, or communities can request available food nearby.',
    volunteerDesc: 'Help deliver food from donors to receivers. Be the bridge!',
    donorFeature1: 'Add food with details & quantity',
    donorFeature2: 'Track request status',
    donorFeature3: 'Manage your donations',
    receiverFeature1: 'Browse available food',
    receiverFeature2: 'Send requests to donors',
    receiverFeature3: 'Track incoming deliveries',
    volunteerFeature1: 'View delivery tasks',
    volunteerFeature2: 'Accept & complete deliveries',
    volunteerFeature3: 'Track pickup & drop locations',
    
    // Live Map Section
    liveMapTitle: 'Live Distribution Map',
    liveMapSubtitle: 'Track food donations, volunteer routes, and distribution centers in real-time',
    donationPoints: 'Donation Points',
    volunteerRoutes: 'Volunteer Routes',
    distributionCenters: 'Distribution Centers',
    viewFullMap: 'View Full Map',
    activeDonations: 'Active Donations',
    activeVolunteers: 'Active Volunteers',
    deliveriesCompleted: 'Deliveries Completed',
    
    // Live Map Page
    liveMapPageTitle: 'Live Distribution Map',
    liveMapPageSubtitle: 'Real-time view of food donations, volunteer locations, and delivery routes',
    filterAll: 'All',
    filterDonations: 'Donations',
    filterVolunteers: 'Volunteers',
    filterCenters: 'Centers',
    legendDonation: 'Food Donation',
    legendVolunteer: 'Volunteer Route',
    legendCenter: 'Distribution Center',
    mapStats: 'Live Statistics',
    
    // Auth
    signIn: 'Sign In',
    createAccount: 'Create Account',
    email: 'Email Address',
    password: 'Password',
    fullName: 'Full Name',
    phone: 'Phone Number',
    address: 'Address / Location',
    selectRole: 'Select Your Role',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    oneLoginNote: 'One login for all roles — Donor, Receiver & Volunteer',
    
    // Footer
    platform: 'Platform',
    roles: 'Roles',
    about: 'About',
    becomeDonor: 'Become a Donor',
    registerNGO: 'Register as NGO',
    joinVolunteer: 'Join as Volunteer',
    ourMission: 'Our Mission',
    contactUs: 'Contact Us',
    privacyPolicy: 'Privacy Policy',
    footerTagline: 'Bridging the gap between surplus food and hungry hearts.',
    footerCopyright: 'Anna Setu — Reduce Food Waste, Feed the Needy 🌱',
    signUp: 'Sign Up',
    
    // Dashboards
    receiverDashboard: 'Receiver Dashboard',
    volunteerDashboard: 'Volunteer Dashboard',
    donorDashboard: 'Donor Dashboard',
    refresh: 'Refresh',
    availableFood: 'Available Food',
    myRequests: 'My Requests',
    deliveries: 'Deliveries',
    map: 'Map',
    available: 'Available',
    myActive: 'My Active',
    completed: 'Completed',
    requestFood: 'Request Food',
    acceptTask: 'Accept Task',
    markPicked: 'Mark Picked',
    markDelivered: 'Mark Delivered',
    loginToRequest: 'Please login to request food!',
    loginToAccept: 'Please login to accept tasks!',
  },

  hi: {
    home: 'होम',
    liveMap: 'लाइव मैप',
    dashboard: 'डैशबोर्ड',
    login: 'लॉग इन',
    logout: 'लॉग आउट',
    heroTitle1: 'बर्बादी कम करें,',
    heroTitle2: 'समुदायों को खिलाएं',
    heroSubtitle: 'अन्ना सेतु अतिरिक्त भोजन को दानदाताओं से स्थानीय एनजीओ और स्वयंसेवकों से जोड़ता है ताकि कोई भूखा न रहे।',
    getStarted: 'अभी शुरू करें',
    goToDashboard: 'डैशबोर्ड पर जाएं',
    welcomeBack: 'वापसी पर स्वागत,',
    mealsRedistributed: 'भोजन पुनर्वितरित',
    activeDonors: 'सक्रिय दानदाता',
    ngosAndShelters: 'एनजीओ और आश्रय',
    volunteers: 'स्वयंसेवक',
    howItWorks: 'यह कैसे काम करता है',
    simpleSteps: 'बदलाव लाने के सरल कदम',
    donorListsFood: 'दानदाता भोजन सूचीबद्ध करता है',
    donorListsFoodDesc: 'रेस्तरां और व्यक्ति अतिरिक्त भोजन को विवरण और समाप्ति समय के साथ सूचीबद्ध करते हैं।',
    receiverRequests: 'प्राप्तकर्ता अनुरोध',
    receiverRequestsDesc: 'एनजीओ और आश्रय उपलब्ध भोजन ब्राउज़ करते हैं और अनुरोध भेजते हैं।',
    volunteerDelivers: 'स्वयंसेवक डिलीवर करता है',
    volunteerDeliversDesc: 'स्वयंसेवक भोजन उठाते हैं और प्राप्तकर्ता तक पहुंचाते हैं।',
    impactMade: 'प्रभाव बना!',
    impactMadeDesc: 'भोजन जरूरतमंदों तक पहुंचता है। शून्य बर्बादी, शून्य भूख।',
    joinAs: 'इस रूप में जुड़ें',
    chooseRole: 'अपनी भूमिका चुनें और प्रभाव डालना शुरू करें',
    donor: 'दानदाता',
    receiver: 'प्राप्तकर्ता',
    volunteer: 'स्वयंसेवक',
    donorDesc: 'अतिरिक्त भोजन है? अन्ना सेतु पर सूचीबद्ध करें और जरूरतमंदों की मदद करें।',
    receiverDesc: 'एनजीओ, आश्रय, या समुदाय पास में उपलब्ध भोजन का अनुरोध कर सकते हैं।',
    volunteerDesc: 'दानदाताओं से प्राप्तकर्ताओं तक भोजन पहुंचाने में मदद करें।',
    donorFeature1: 'विवरण और मात्रा के साथ भोजन जोड़ें',
    donorFeature2: 'अनुरोध स्थिति ट्रैक करें',
    donorFeature3: 'अपने दान प्रबंधित करें',
    receiverFeature1: 'उपलब्ध भोजन ब्राउज़ करें',
    receiverFeature2: 'दानदाताओं को अनुरोध भेजें',
    receiverFeature3: 'आने वाली डिलीवरी ट्रैक करें',
    volunteerFeature1: 'डिलीवरी कार्य देखें',
    volunteerFeature2: 'डिलीवरी स्वीकार करें और पूर्ण करें',
    volunteerFeature3: 'पिकअप और ड्रॉप स्थान ट्रैक करें',
    liveMapTitle: 'लाइव वितरण मैप',
    liveMapSubtitle: 'वास्तविक समय में भोजन दान, स्वयंसेवक मार्ग और वितरण केंद्र ट्रैक करें',
    donationPoints: 'दान बिंदु',
    volunteerRoutes: 'स्वयंसेवक मार्ग',
    distributionCenters: 'वितरण केंद्र',
    viewFullMap: 'पूरा मैप देखें',
    activeDonations: 'सक्रिय दान',
    activeVolunteers: 'सक्रिय स्वयंसेवक',
    deliveriesCompleted: 'डिलीवरी पूर्ण',
    liveMapPageTitle: 'लाइव वितरण मैप',
    liveMapPageSubtitle: 'भोजन दान, स्वयंसेवक स्थानों और डिलीवरी मार्गों का वास्तविक समय दृश्य',
    filterAll: 'सभी',
    filterDonations: 'दान',
    filterVolunteers: 'स्वयंसेवक',
    filterCenters: 'केंद्र',
    legendDonation: 'भोजन दान',
    legendVolunteer: 'स्वयंसेवक मार्ग',
    legendCenter: 'वितरण केंद्र',
    mapStats: 'लाइव आंकड़े',
    signIn: 'साइन इन',
    createAccount: 'खाता बनाएं',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    phone: 'फोन नंबर',
    address: 'पता / स्थान',
    selectRole: 'अपनी भूमिका चुनें',
    noAccount: 'खाता नहीं है?',
    haveAccount: 'पहले से खाता है?',
    oneLoginNote: 'सभी भूमिकाओं के लिए एक लॉगिन — दानदाता, प्राप्तकर्ता और स्वयंसेवक',
    platform: 'प्लेटफ़ॉर्म',
    roles: 'भूमिकाएं',
    about: 'हमारे बारे में',
    becomeDonor: 'दानदाता बनें',
    registerNGO: 'एनजीओ के रूप में पंजीकरण करें',
    joinVolunteer: 'स्वयंसेवक के रूप में जुड़ें',
    ourMission: 'हमारा मिशन',
    contactUs: 'संपर्क करें',
    privacyPolicy: 'गोपनीयता नीति',
    footerTagline: 'अतिरिक्त भोजन और भूखे दिलों के बीच सेतु।',
    footerCopyright: 'अन्ना सेतु — भोजन की बर्बादी कम करें, जरूरतमंदों को खिलाएं 🌱',
    signUp: 'साइन अप',
    receiverDashboard: 'प्राप्तकर्ता डैशबोर्ड',
    volunteerDashboard: 'स्वयंसेवक डैशबोर्ड',
    donorDashboard: 'दानदाता डैशबोर्ड',
    refresh: 'रिफ्रेश',
    availableFood: 'उपलब्ध भोजन',
    myRequests: 'मेरे अनुरोध',
    deliveries: 'डिलीवरी',
    map: 'मैप',
    available: 'उपलब्ध',
    myActive: 'मेरे सक्रिय',
    completed: 'पूर्ण',
    requestFood: 'भोजन का अनुरोध करें',
    acceptTask: 'कार्य स्वीकार करें',
    markPicked: 'पिक किया गया चिह्नित करें',
    markDelivered: 'डिलीवर किया गया चिह्नित करें',
    loginToRequest: 'कृपया भोजन अनुरोध करने के लिए लॉगिन करें!',
    loginToAccept: 'कृपया कार्य स्वीकार करने के लिए लॉगिन करें!',
  },

  kn: {
    home: 'ಮುಖಪುಟ',
    liveMap: 'ಲೈವ್ ನಕ್ಷೆ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    login: 'ಲಾಗಿನ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    heroTitle1: 'ವ್ಯರ್ಥವನ್ನು ಕಡಿಮೆ ಮಾಡಿ,',
    heroTitle2: 'ಸಮುದಾಯಗಳಿಗೆ ಊಟ ನೀಡಿ',
    heroSubtitle: 'ಅನ್ನ ಸೇತು ಹೆಚ್ಚುವರಿ ಆಹಾರವನ್ನು ದಾನಿಗಳಿಂದ ಸ್ಥಳೀಯ ಎನ್‌ಜಿಒಗಳು ಮತ್ತು ಸ್ವಯಂಸೇವಕರಿಗೆ ಸಂಪರ್ಕಿಸುತ್ತದೆ.',
    getStarted: 'ಈಗ ಪ್ರಾರಂಭಿಸಿ',
    goToDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ',
    welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ,',
    mealsRedistributed: 'ಊಟ ಮರುಹಂಚಿಕೆ',
    activeDonors: 'ಸಕ್ರಿಯ ದಾನಿಗಳು',
    ngosAndShelters: 'ಎನ್‌ಜಿಒ ಮತ್ತು ಆಶ್ರಯ',
    volunteers: 'ಸ್ವಯಂಸೇವಕರು',
    howItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    simpleSteps: 'ಬದಲಾವಣೆ ಮಾಡಲು ಸರಳ ಹಂತಗಳು',
    donorListsFood: 'ದಾನಿ ಆಹಾರ ಪಟ್ಟಿ ಮಾಡುತ್ತಾರೆ',
    donorListsFoodDesc: 'ರೆಸ್ಟೋರೆಂಟ್‌ಗಳು ಹೆಚ್ಚುವರಿ ಆಹಾರವನ್ನು ವಿವರಗಳೊಂದಿಗೆ ಪಟ್ಟಿ ಮಾಡುತ್ತವೆ.',
    receiverRequests: 'ಸ್ವೀಕೃತದಾರ ವಿನಂತಿಗಳು',
    receiverRequestsDesc: 'ಎನ್‌ಜಿಒಗಳು ಲಭ್ಯವಿರುವ ಆಹಾರವನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ ವಿನಂತಿ ಕಳುಹಿಸುತ್ತವೆ.',
    volunteerDelivers: 'ಸ್ವಯಂಸೇವಕ ತಲುಪಿಸುತ್ತಾರೆ',
    volunteerDeliversDesc: 'ಸ್ವಯಂಸೇವಕರು ಆಹಾರವನ್ನು ಎತ್ತಿಕೊಂಡು ಸ್ವೀಕೃತದಾರರಿಗೆ ತಲುಪಿಸುತ್ತಾರೆ.',
    impactMade: 'ಪರಿಣಾಮ ಮಾಡಿದ್ದೇವೆ!',
    impactMadeDesc: 'ಆಹಾರ ಅಗತ್ಯವಿರುವವರಿಗೆ ತಲುಪುತ್ತದೆ.',
    joinAs: 'ಇದರಂತೆ ಸೇರಿ',
    chooseRole: 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    donor: 'ದಾನಿ',
    receiver: 'ಸ್ವೀಕೃತದಾರ',
    volunteer: 'ಸ್ವಯಂಸೇವಕ',
    donorDesc: 'ಹೆಚ್ಚುವರಿ ಆಹಾರವಿದೆಯೇ? ಅನ್ನ ಸೇತುವಿನಲ್ಲಿ ಪಟ್ಟಿ ಮಾಡಿ.',
    receiverDesc: 'ಎನ್‌ಜಿಒಗಳು ಹತ್ತಿರದ ಆಹಾರಕ್ಕೆ ವಿನಂತಿಸಬಹುದು.',
    volunteerDesc: 'ದಾನಿಗಳಿಂದ ಸ್ವೀಕೃತದಾರರಿಗೆ ಆಹಾರ ತಲುಪಿಸಲು ಸಹಾಯ ಮಾಡಿ!',
    donorFeature1: 'ವಿವರ ಮತ್ತು ಪ್ರಮಾಣದೊಂದಿಗೆ ಆಹಾರ ಸೇರಿಸಿ',
    donorFeature2: 'ವಿನಂತಿ ಸ್ಥಿತಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    donorFeature3: 'ನಿಮ್ಮ ದಾನಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    receiverFeature1: 'ಲಭ್ಯವಿರುವ ಆಹಾರ ಬ್ರೌಸ್ ಮಾಡಿ',
    receiverFeature2: 'ದಾನಿಗಳಿಗೆ ವಿನಂತಿ ಕಳುಹಿಸಿ',
    receiverFeature3: 'ಬರುತ್ತಿರುವ ಡೆಲಿವರಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    volunteerFeature1: 'ಡೆಲಿವರಿ ಕಾರ್ಯಗಳನ್ನು ನೋಡಿ',
    volunteerFeature2: 'ಡೆಲಿವರಿ ಸ್ವೀಕರಿಸಿ ಮತ್ತು ಪೂರ್ಣಗೊಳಿಸಿ',
    volunteerFeature3: 'ಪಿಕಪ್ ಮತ್ತು ಡ್ರಾಪ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    liveMapTitle: 'ಲೈವ್ ವಿತರಣೆ ನಕ್ಷೆ',
    liveMapSubtitle: 'ನೈಜ ಸಮಯದಲ್ಲಿ ಆಹಾರ ದಾನ ಮತ್ತು ಸ್ವಯಂಸೇವಕ ಮಾರ್ಗಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    donationPoints: 'ದಾನ ಬಿಂದುಗಳು',
    volunteerRoutes: 'ಸ್ವಯಂಸೇವಕ ಮಾರ್ಗಗಳು',
    distributionCenters: 'ವಿತರಣೆ ಕೇಂದ್ರಗಳು',
    viewFullMap: 'ಪೂರ್ಣ ನಕ್ಷೆ ನೋಡಿ',
    activeDonations: 'ಸಕ್ರಿಯ ದಾನಗಳು',
    activeVolunteers: 'ಸಕ್ರಿಯ ಸ್ವಯಂಸೇವಕರು',
    deliveriesCompleted: 'ಡೆಲಿವರಿ ಪೂರ್ಣ',
    liveMapPageTitle: 'ಲೈವ್ ವಿತರಣೆ ನಕ್ಷೆ',
    liveMapPageSubtitle: 'ಆಹಾರ ದಾನಗಳ ನೈಜ ಸಮಯ ನೋಟ',
    filterAll: 'ಎಲ್ಲಾ',
    filterDonations: 'ದಾನಗಳು',
    filterVolunteers: 'ಸ್ವಯಂಸೇವಕರು',
    filterCenters: 'ಕೇಂದ್ರಗಳು',
    legendDonation: 'ಆಹಾರ ದಾನ',
    legendVolunteer: 'ಸ್ವಯಂಸೇವಕ ಮಾರ್ಗ',
    legendCenter: 'ವಿತರಣೆ ಕೇಂದ್ರ',
    mapStats: 'ಲೈವ್ ಅಂಕಿಅಂಶ',
    signIn: 'ಸೈನ್ ಇನ್',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    email: 'ಇಮೇಲ್ ವಿಳಾಸ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು',
    phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    address: 'ವಿಳಾಸ / ಸ್ಥಳ',
    selectRole: 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    haveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    oneLoginNote: 'ಎಲ್ಲಾ ಪಾತ್ರಗಳಿಗೆ ಒಂದು ಲಾಗಿನ್',
    platform: 'ಪ್ಲಾಟ್‌ಫಾರ್ಮ್',
    roles: 'ಪಾತ್ರಗಳು',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    becomeDonor: 'ದಾನಿಯಾಗಿ',
    registerNGO: 'ಎನ್‌ಜಿಒ ಆಗಿ ನೋಂದಣಿ',
    joinVolunteer: 'ಸ್ವಯಂಸೇವಕರಾಗಿ ಸೇರಿ',
    ourMission: 'ನಮ್ಮ ಮಿಷನ್',
    contactUs: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
    privacyPolicy: 'ಗೌಪ್ಯತೆ ನೀತಿ',
    footerTagline: 'ಹೆಚ್ಚುವರಿ ಆಹಾರ ಮತ್ತು ಹಸಿದ ಹೃದಯಗಳ ನಡುವೆ ಸೇತು.',
    footerCopyright: 'ಅನ್ನ ಸೇತು — ಆಹಾರ ವ್ಯರ್ಥ ಕಡಿಮೆ ಮಾಡಿ 🌱',
    signUp: 'ಸೈನ್ ಅಪ್',
    receiverDashboard: 'ಸ್ವೀಕೃತದಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    volunteerDashboard: 'ಸ್ವಯಂಸೇವಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    donorDashboard: 'ದಾನಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    refresh: 'ರಿಫ್ರೆಶ್',
    availableFood: 'ಲಭ್ಯವಿರುವ ಆಹಾರ',
    myRequests: 'ನನ್ನ ವಿನಂತಿಗಳು',
    deliveries: 'ಡೆಲಿವರಿಗಳು',
    map: 'ನಕ್ಷೆ',
    available: 'ಲಭ್ಯ',
    myActive: 'ನನ್ನ ಸಕ್ರಿಯ',
    completed: 'ಪೂರ್ಣ',
    requestFood: 'ಆಹಾರಕ್ಕೆ ವಿನಂತಿಸಿ',
    acceptTask: 'ಕಾರ್ಯ ಸ್ವೀಕರಿಸಿ',
    markPicked: 'ಪಿಕ್ ಆಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    markDelivered: 'ತಲುಪಿಸಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    loginToRequest: 'ದಯವಿಟ್ಟು ಆಹಾರ ವಿನಂತಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ!',
    loginToAccept: 'ದಯವಿಟ್ಟು ಕಾರ್ಯ ಸ್ವೀಕರಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ!',
  },

  ta: {
    home: 'முகப்பு',
    liveMap: 'நேரடி வரைபடம்',
    dashboard: 'டாஷ்போர்டு',
    login: 'உள்நுழை',
    logout: 'வெளியேறு',
    heroTitle1: 'வீணை குறையுங்கள்,',
    heroTitle2: 'சமூகங்களுக்கு உணவளியுங்கள்',
    heroSubtitle: 'அன்ன சேது உபரி உணவை நன்கொடையாளர்களிடமிருந்து தன்னார்வலர்கள் மற்றும் என்ஜிஓக்களுடன் இணைக்கிறது.',
    getStarted: 'இப்போது தொடங்குங்கள்',
    goToDashboard: 'டாஷ்போர்டுக்கு செல்',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்,',
    mealsRedistributed: 'உணவு மறுவிநியோகம்',
    activeDonors: 'செயலில் உள்ள நன்கொடையாளர்கள்',
    ngosAndShelters: 'என்ஜிஓ மற்றும் தங்குமிடங்கள்',
    volunteers: 'தன்னார்வலர்கள்',
    howItWorks: 'இது எப்படி வேலை செய்கிறது',
    simpleSteps: 'மாற்றத்தை ஏற்படுத்த எளிய படிகள்',
    donorListsFood: 'நன்கொடையாளர் உணவைப் பட்டியலிடுகிறார்',
    donorListsFoodDesc: 'உணவகங்கள் உபரி உணவை விவரங்களுடன் பட்டியலிடுகின்றன.',
    receiverRequests: 'பெறுநர் கோரிக்கைகள்',
    receiverRequestsDesc: 'என்ஜிஓக்கள் கிடைக்கும் உணவை உலாவி கோரிக்கை அனுப்புகின்றன.',
    volunteerDelivers: 'தன்னார்வலர் விநியோகிக்கிறார்',
    volunteerDeliversDesc: 'தன்னார்வலர்கள் உணவை எடுத்து பெறுநருக்கு வழங்குகிறார்கள்.',
    impactMade: 'தாக்கம் ஏற்பட்டது!',
    impactMadeDesc: 'உணவு தேவையானவர்களை அடைகிறது.',
    joinAs: 'இணையுங்கள்',
    chooseRole: 'உங்கள் பங்கை தேர்வு செய்யுங்கள்',
    donor: 'நன்கொடையாளர்',
    receiver: 'பெறுநர்',
    volunteer: 'தன்னார்வலர்',
    donorDesc: 'உபரி உணவு உள்ளதா? அன்ன சேதுவில் பட்டியலிடுங்கள்.',
    receiverDesc: 'என்ஜிஓக்கள் அருகிலுள்ள உணவைக் கோரலாம்.',
    volunteerDesc: 'உணவை நன்கொடையாளர்களிடமிருந்து பெறுநர்களுக்கு அனுப்ப உதவுங்கள்!',
    donorFeature1: 'விவரம் மற்றும் அளவுடன் உணவு சேர்',
    donorFeature2: 'கோரிக்கை நிலையை கண்காணி',
    donorFeature3: 'உங்கள் நன்கொடைகளை நிர்வகி',
    receiverFeature1: 'கிடைக்கும் உணவை உலாவு',
    receiverFeature2: 'நன்கொடையாளர்களுக்கு கோரிக்கை அனுப்பு',
    receiverFeature3: 'வரும் விநியோகத்தை கண்காணி',
    volunteerFeature1: 'விநியோக பணிகளைப் பார்',
    volunteerFeature2: 'விநியோகத்தை ஏற்று முடி',
    volunteerFeature3: 'பிக்அப் மற்றும் டிராப் கண்காணி',
    liveMapTitle: 'நேரடி விநியோக வரைபடம்',
    liveMapSubtitle: 'நிகழ் நேரத்தில் உணவு நன்கொடை மற்றும் தன்னார்வலர் பாதைகளைக் கண்காணியுங்கள்',
    viewFullMap: 'முழு வரைபடம் காண்',
    signIn: 'உள்நுழை',
    createAccount: 'கணக்கு உருவாக்கு',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    fullName: 'முழு பெயர்',
    phone: 'தொலைபேசி எண்',
    address: 'முகவரி / இடம்',
    selectRole: 'உங்கள் பங்கை தேர்வு செய்',
    noAccount: 'கணக்கு இல்லையா?',
    haveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    signUp: 'பதிவு செய்',
    footerTagline: 'உபரி உணவுக்கும் பசித்த இதயங்களுக்கும் இடையே பாலம்.',
    footerCopyright: 'அன்ன சேது — உணவு வீணை குறையுங்கள் 🌱',
    platform: 'தளம்',
    roles: 'பாத்திரங்கள்',
    about: 'எங்களைப் பற்றி',
    donationPoints: 'நன்கொடை புள்ளிகள்',
    volunteerRoutes: 'தன்னார்வலர் பாதைகள்',
    distributionCenters: 'விநியோக மையங்கள்',
    activeDonations: 'செயலில் நன்கொடைகள்',
    activeVolunteers: 'செயலில் தன்னார்வலர்கள்',
    deliveriesCompleted: 'விநியோகம் முடிந்தது',
    liveMapPageTitle: 'நேரடி விநியோக வரைபடம்',
    liveMapPageSubtitle: 'உணவு நன்கொடைகளின் நிகழ் நேர காட்சி',
    filterAll: 'அனைத்தும்',
    filterDonations: 'நன்கொடைகள்',
    filterVolunteers: 'தன்னார்வலர்கள்',
    filterCenters: 'மையங்கள்',
    legendDonation: 'உணவு நன்கொடை',
    legendVolunteer: 'தன்னார்வலர் பாதை',
    legendCenter: 'விநியோக மையம்',
    mapStats: 'நேரடி புள்ளிவிவரங்கள்',
    oneLoginNote: 'அனைத்து பாத்திரங்களுக்கும் ஒரு உள்நுழைவு',
    becomeDonor: 'நன்கொடையாளராகு',
    registerNGO: 'என்ஜிஓ ஆக பதிவு செய்',
    joinVolunteer: 'தன்னார்வலராக இணை',
    ourMission: 'எங்கள் நோக்கம்',
    contactUs: 'எங்களை தொடர்பு கொள்',
    privacyPolicy: 'தனியுரிமை கொள்கை',
    receiverDashboard: 'பெறுநர் டாஷ்போர்டு',
    volunteerDashboard: 'தன்னார்வலர் டாஷ்போர்டு',
    donorDashboard: 'நன்கொடையாளர் டாஷ்போர்டு',
    refresh: 'புதுப்பி',
    availableFood: 'கிடைக்கும் உணவு',
    myRequests: 'என் கோரிக்கைகள்',
    deliveries: 'விநியோகங்கள்',
    map: 'வரைபடம்',
    available: 'கிடைக்கும்',
    myActive: 'என் செயலில்',
    completed: 'முடிந்தது',
    requestFood: 'உணவு கோரு',
    acceptTask: 'பணியை ஏற்கவும்',
    markPicked: 'எடுக்கப்பட்டது குறி',
    markDelivered: 'வழங்கப்பட்டது குறி',
    loginToRequest: 'உணவு கோர உள்நுழையவும்!',
    loginToAccept: 'பணி ஏற்க உள்நுழையவும்!',
  },

  te: {
    home: 'హోమ్',
    liveMap: 'లైవ్ మ్యాప్',
    dashboard: 'డాష్‌బోర్డ్',
    login: 'లాగిన్',
    logout: 'లాగ్ అవుట్',
    heroTitle1: 'వృధాను తగ్గించండి,',
    heroTitle2: 'సమాజాలకు ఆహారం అందించండి',
    heroSubtitle: 'అన్న సేతు మిగులు ఆహారాన్ని దాతల నుండి స్థానిక NGOలు మరియు వాలంటీర్లతో కలుపుతుంది.',
    getStarted: 'ఇప్పుడు ప్రారంభించండి',
    goToDashboard: 'డాష్‌బోర్డ్‌కు వెళ్ళండి',
    welcomeBack: 'తిరిగి స్వాగతం,',
    mealsRedistributed: 'భోజనాలు పంపిణీ',
    activeDonors: 'సక్రియ దాతలు',
    ngosAndShelters: 'NGOలు & ఆశ్రయాలు',
    volunteers: 'వాలంటీర్లు',
    howItWorks: 'ఇది ఎలా పనిచేస్తుంది',
    simpleSteps: 'మార్పు చేయడానికి సరళ అడుగులు',
    joinAs: 'ఇలా చేరండి',
    chooseRole: 'మీ పాత్రను ఎంచుకోండి',
    donor: 'దాత',
    receiver: 'స్వీకర్త',
    volunteer: 'వాలంటీర్',
    getStarted: 'ఇప్పుడు ప్రారంభించండి',
    signIn: 'సైన్ ఇన్',
    createAccount: 'ఖాతా సృష్టించు',
    email: 'ఇమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    fullName: 'పూర్తి పేరు',
    phone: 'ఫోన్ నంబర్',
    address: 'చిరునామా / స్థానం',
    selectRole: 'మీ పాత్రను ఎంచుకోండి',
    signUp: 'సైన్ అప్',
    liveMapTitle: 'లైవ్ పంపిణీ మ్యాప్',
    liveMapSubtitle: 'నిజ సమయంలో ఆహార దానాలు మరియు వాలంటీర్ మార్గాలను ట్రాక్ చేయండి',
    viewFullMap: 'పూర్తి మ్యాప్ చూడండి',
    footerTagline: 'మిగులు ఆహారం మరియు ఆకలి గుండెల మధ్య వంతెన.',
    footerCopyright: 'అన్న సేతు — ఆహార వృధాను తగ్గించండి 🌱',
    donorListsFood: 'దాత ఆహారం జాబితా చేస్తారు',
    donorListsFoodDesc: 'రెస్టారెంట్లు మిగులు ఆహారాన్ని వివరాలతో జాబితా చేస్తాయి.',
    receiverRequests: 'స్వీకర్త అభ్యర్థనలు',
    receiverRequestsDesc: 'NGOలు అందుబాటులో ఉన్న ఆహారాన్ని బ్రౌజ్ చేసి అభ్యర్థన పంపుతాయి.',
    volunteerDelivers: 'వాలంటీర్ డెలివరీ చేస్తారు',
    volunteerDeliversDesc: 'వాలంటీర్లు ఆహారాన్ని తీసుకొని స్వీకర్తకు అందజేస్తారు.',
    impactMade: 'ప్రభావం సృష్టించారు!',
    impactMadeDesc: 'ఆహారం అవసరమైన వారికి చేరుతుంది.',
    donorDesc: 'మిగులు ఆహారం ఉందా? అన్న సేతులో జాబితా చేయండి.',
    receiverDesc: 'NGOలు సమీపంలోని ఆహారానికి అభ్యర్థించవచ్చు.',
    volunteerDesc: 'దాతల నుండి స్వీకర్తలకు ఆహారం చేరవేయడంలో సహాయపడండి!',
    platform: 'ప్లాట్‌ఫారమ్',
    roles: 'పాత్రలు',
    about: 'మా గురించి',
    refresh: 'రిఫ్రెష్',
    requestFood: 'ఆహారం అభ్యర్థించు',
    acceptTask: 'పనిని అంగీకరించు',
  },
};

// Fill missing keys with English fallback
Object.keys(translations).forEach(lang => {
  if (lang !== 'en') {
    Object.keys(translations.en).forEach(key => {
      if (!translations[lang][key]) {
        translations[lang][key] = translations.en[key];
      }
    });
  }
});

const LanguageContext = createContext(null);

const LANGUAGES = [
  { code: 'en', label: 'EN', name: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'HI', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'kn', label: 'KN', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ta', label: 'TA', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', label: 'TE', name: 'తెలుగు', flag: '🇮🇳' },
];

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('annaSetu_lang') || 'en';
  });

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('annaSetu_lang', newLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
